spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/household
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

app:
  jwt:
    secret: ThisIsAReallyStrongJwtSecretKeyWithMoreThan32Chars
    expiration-minutes: 60

logging:
  level:
    org.springframework.security: DEBUG